from django.urls import path
from .views import (
    admin_audit_log,
    admin_reanalyse_object,
    admin_list_all_datafiles,
    admin_re_evaluate_datafiles,
    admin_re_evaluate_run,
    admin_link_datafiles_to_object,
    admin_unlink_datafiles_from_objects,
    admin_health,
    admin_trigger_cleanup_downloads,
    admin_trigger_reconcile,
    admin_trigger_orphans_hashcheck,
    admin_trigger_scan_missing,
    admin_trigger_orphan_objects,
    admin_trigger_unlink_non_light_datafiles,
    admin_trigger_refresh_dashboard_stats,
    admin_trigger_plate_solve_task,
    admin_trigger_re_evaluate_plate_solved,
    admin_run_set_date,
    admin_run_recompute_date,
    admin_clear_override_flag,
    admin_clear_all_overrides,
    admin_list_override_flags,
    admin_get_banner,
    admin_set_banner,
    admin_clear_banner,
    banner_info,
    admin_delete_object_aliases,
    admin_update_object_identifiers,
    admin_get_exposure_type_discrepancies,
    admin_update_exposure_type_user,
    admin_get_spectrograph_files,
    admin_update_spectrograph,
    admin_get_unsolved_plate_files,
    admin_trigger_plate_solve,
    admin_plate_solve_stats,
    admin_get_plate_solving_task_enabled,
    admin_set_plate_solving_task_enabled,
    admin_get_observation_runs_for_plate_solving,
    admin_aux_objects_stats,
    admin_trigger_aux_objects,
    admin_trigger_aux_objects_queue,
    admin_get_aux_objects_task_enabled,
    admin_set_aux_objects_task_enabled,
)
from objects.api.solar_image_views import (
    admin_delete_solar_system_image,
    admin_list_solar_system_images,
    admin_upload_solar_system_image,
)

app_name = 'adminops-api'

urlpatterns = [
    path('audit-log/', admin_audit_log, name='audit_log'),
    path('health/', admin_health, name='health'),
    path('maintenance/cleanup-downloads/', admin_trigger_cleanup_downloads, name='cleanup_downloads'),
    path('maintenance/reconcile/', admin_trigger_reconcile, name='reconcile'),
    path('maintenance/orphans-hashcheck/', admin_trigger_orphans_hashcheck, name='orphans_hashcheck'),
    path('maintenance/scan-missing/', admin_trigger_scan_missing, name='scan_missing'),
    path('maintenance/orphan-objects/', admin_trigger_orphan_objects, name='orphan_objects'),
    path('maintenance/unlink-non-light-datafiles/', admin_trigger_unlink_non_light_datafiles, name='unlink_non_light_datafiles'),
    path('maintenance/refresh-dashboard-stats/', admin_trigger_refresh_dashboard_stats, name='refresh_dashboard_stats'),
    path('maintenance/plate-solving/', admin_trigger_plate_solve_task, name='trigger_plate_solve_task'),
    path('maintenance/re-evaluate-plate-solved/', admin_trigger_re_evaluate_plate_solved, name='trigger_re_evaluate_plate_solved'),
    path('runs/<int:run_id>/set-date/', admin_run_set_date, name='run_set_date'),
    path('runs/<int:run_id>/recompute-date/', admin_run_recompute_date, name='run_recompute_date'),
    path('runs/<int:run_id>/re-evaluate/', admin_re_evaluate_run, name='run_re_evaluate'),
    path('override-flags/<str:model_type>/<int:instance_id>/<str:field_name>/clear/', admin_clear_override_flag, name='clear_override_flag'),
    path('override-flags/<str:model_type>/<int:instance_id>/clear-all/', admin_clear_all_overrides, name='clear_all_overrides'),
    path('override-flags/list/', admin_list_override_flags, name='list_override_flags'),
    path('banner/', admin_get_banner, name='get_banner'),
    path('banner/set', admin_set_banner, name='set_banner'),
    path('banner/clear', admin_clear_banner, name='clear_banner'),
    path('banner-info/', banner_info, name='banner_info'),
    path('objects/<int:object_id>/delete-aliases/', admin_delete_object_aliases, name='delete_object_aliases'),
    path('objects/<int:object_id>/update-identifiers/', admin_update_object_identifiers, name='update_object_identifiers'),
    path('objects/<int:object_id>/reanalyse/', admin_reanalyse_object, name='reanalyse_object'),
    path('objects/solar-system-images/', admin_list_solar_system_images, name='solar_system_images_list'),
    path('objects/solar-system-images/upload/', admin_upload_solar_system_image, name='solar_system_images_upload'),
    path('objects/solar-system-images/<int:object_id>/', admin_delete_solar_system_image, name='solar_system_images_delete'),
    # DataFiles list (all) and re-evaluate
    path('datafiles/', admin_list_all_datafiles, name='list_all_datafiles'),
    path('datafiles/re-evaluate/', admin_re_evaluate_datafiles, name='re_evaluate_datafiles'),
    path('datafiles/link-objects/', admin_link_datafiles_to_object, name='link_datafiles_to_object'),
    path('datafiles/unlink-objects/', admin_unlink_datafiles_from_objects, name='unlink_datafiles_from_objects'),
    # Exposure type classification endpoints
    path('datafiles/discrepancies/', admin_get_exposure_type_discrepancies, name='exposure_type_discrepancies'),
    path('datafiles/<int:pk>/exposure-type-user/', admin_update_exposure_type_user, name='update_exposure_type_user'),
    # Spectrograph management endpoints
    path('datafiles/spectrograph/', admin_get_spectrograph_files, name='spectrograph_files'),
    path('datafiles/<int:pk>/spectrograph/', admin_update_spectrograph, name='update_spectrograph'),
    # Plate solving endpoints
    path('datafiles/plate-solving/unsolved/', admin_get_unsolved_plate_files, name='unsolved_plate_files'),
    path('datafiles/plate-solving/trigger/', admin_trigger_plate_solve, name='trigger_plate_solve'),
    path('datafiles/plate-solving/stats/', admin_plate_solve_stats, name='plate_solve_stats'),
    path('datafiles/plate-solving/task-enabled/', admin_get_plate_solving_task_enabled, name='plate_solving_task_enabled'),
    path('datafiles/plate-solving/task-enabled/set/', admin_set_plate_solving_task_enabled, name='set_plate_solving_task_enabled'),
    path('datafiles/plate-solving/observation-runs/', admin_get_observation_runs_for_plate_solving, name='observation_runs_for_plate_solving'),
    path('runs/aux-objects/stats/', admin_aux_objects_stats, name='aux_objects_stats'),
    path('runs/aux-objects/trigger/', admin_trigger_aux_objects, name='trigger_aux_objects'),
    path('runs/aux-objects/queue/', admin_trigger_aux_objects_queue, name='trigger_aux_objects_queue'),
    path('runs/aux-objects/task-enabled/', admin_get_aux_objects_task_enabled, name='aux_objects_task_enabled'),
    path('runs/aux-objects/task-enabled/set/', admin_set_aux_objects_task_enabled, name='set_aux_objects_task_enabled'),
]




