# Generated by Django 4.2.4 on 2023-09-23 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obs_run', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationrun',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_run', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observationrun',
            name='readonly_users',
            field=models.ManyToManyField(blank=True, related_name='readonly_run', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observationrun',
            name='readwrite_users',
            field=models.ManyToManyField(blank=True, related_name='readwrite_run', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observationrun',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
        migrations.AddField(
            model_name='historicalobservationrun',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='observation_run',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='obs_run.observationrun'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='observation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obs_run.observationrun'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
