# Generated by Django 5.2.7 on 2025-10-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_run', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='content_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='content_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='exposure_type',
            field=models.CharField(choices=[('BI', 'Bias'), ('DA', 'Dark'), ('FL', 'Flat'), ('LI', 'Light'), ('WA', 'Wave'), ('UK', 'Unknown')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicaldatafile',
            name='exposure_type',
            field=models.CharField(choices=[('BI', 'Bias'), ('DA', 'Dark'), ('FL', 'Flat'), ('LI', 'Light'), ('WA', 'Wave'), ('UK', 'Unknown')], default='UK', max_length=2),
        ),
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_ids', models.JSONField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='queued', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('bytes_total', models.BigIntegerField(default=0)),
                ('bytes_done', models.BigIntegerField(default=0)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_jobs', to='obs_run.observationrun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
