# Generated by Django 5.2.7 on 2025-11-28 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_run', '0003_datafile_content_hash_datafile_file_size_and_more'),
        ('tags', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['observation_run'], name='df_run_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['file_type'], name='df_file_type_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['exposure_type'], name='df_expo_type_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['exptime'], name='df_exptime_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['hjd'], name='df_hjd_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['instrument'], name='df_instrument_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['telescope'], name='df_telescope_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['main_target'], name='df_main_target_idx'),
        ),
        migrations.AddIndex(
            model_name='observationrun',
            index=models.Index(fields=['mid_observation_jd'], name='run_mid_jd_idx'),
        ),
        migrations.AddIndex(
            model_name='observationrun',
            index=models.Index(fields=['reduction_status'], name='run_red_status_idx'),
        ),
        migrations.AddIndex(
            model_name='observationrun',
            index=models.Index(fields=['is_public'], name='run_is_public_idx'),
        ),
    ]
