# Generated by Django 5.2.8 on 2026-01-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_run', '0005_datafile_binning_x_datafile_binning_y_and_more'),
        ('tags', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='exposure_type_ml',
            field=models.CharField(blank=True, choices=[('BI', 'Bias'), ('DA', 'Dark'), ('FL', 'Flat'), ('LI', 'Light'), ('WA', 'Wave'), ('UK', 'Unknown')], default='UK', help_text='Exposure type determined by ML classification model', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='exposure_type_ml_abstained',
            field=models.BooleanField(default=False, help_text='Whether the ML model abstained (returned unknown)'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='exposure_type_ml_confidence',
            field=models.FloatField(blank=True, default=None, help_text='Confidence score from ML classification (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='exposure_type_user',
            field=models.CharField(blank=True, choices=[('BI', 'Bias'), ('DA', 'Dark'), ('FL', 'Flat'), ('LI', 'Light'), ('WA', 'Wave'), ('UK', 'Unknown')], default=None, help_text='Exposure type manually set by user', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='exposure_type_user_override',
            field=models.BooleanField(default=False, help_text='Override flag to prevent automatic updates to user-set exposure type'),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='exposure_type_ml',
            field=models.CharField(blank=True, choices=[('BI', 'Bias'), ('DA', 'Dark'), ('FL', 'Flat'), ('LI', 'Light'), ('WA', 'Wave'), ('UK', 'Unknown')], default='UK', help_text='Exposure type determined by ML classification model', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='exposure_type_ml_abstained',
            field=models.BooleanField(default=False, help_text='Whether the ML model abstained (returned unknown)'),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='exposure_type_ml_confidence',
            field=models.FloatField(blank=True, default=None, help_text='Confidence score from ML classification (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='exposure_type_user',
            field=models.CharField(blank=True, choices=[('BI', 'Bias'), ('DA', 'Dark'), ('FL', 'Flat'), ('LI', 'Light'), ('WA', 'Wave'), ('UK', 'Unknown')], default=None, help_text='Exposure type manually set by user', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='exposure_type_user_override',
            field=models.BooleanField(default=False, help_text='Override flag to prevent automatic updates to user-set exposure type'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['exposure_type_ml'], name='df_expo_type_ml_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['exposure_type_user'], name='df_expo_type_user_idx'),
        ),
    ]
