# Generated by Django 5.2.8 on 2026-02-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_run', '0006_datafile_exposure_type_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='plate_solve_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='plate_solve_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='plate_solve_tool',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='plate_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_cd1_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_cd1_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_cd2_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_cd2_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_cdelt1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_cdelt2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_crota1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_crota2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_crpix1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_crpix2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_crval1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_crval2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_dec_dms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_field_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_field_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_field_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_orientation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_parity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_pix_scale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_ra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='wcs_ra_hms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='plate_solve_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='plate_solve_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='plate_solve_tool',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='plate_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_cd1_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_cd1_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_cd2_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_cd2_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_cdelt1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_cdelt2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_crota1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_crota2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_crpix1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_crpix2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_crval1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_crval2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_dec_dms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_field_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_field_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_field_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_orientation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_parity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_pix_scale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_ra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='wcs_ra_hms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
