# Generated by Django 5.2.8 on 2026-02-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_run', '0007_datafile_plate_solve_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='re_evaluated_after_plate_solve',
            field=models.BooleanField(default=False, help_text='True if re_evaluate_plate_solved_files has processed this file (avoids double evaluation).'),
        ),
        migrations.AddField(
            model_name='historicaldatafile',
            name='re_evaluated_after_plate_solve',
            field=models.BooleanField(default=False, help_text='True if re_evaluate_plate_solved_files has processed this file (avoids double evaluation).'),
        ),
    ]
