# Generated by Django 6.0.5 on 2026-06-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_run', '0009_observationrun_aux_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobservationrun',
            name='aux_objects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalobservationrun',
            name='aux_objects_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalobservationrun',
            name='aux_objects_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalobservationrun',
            name='aux_objects_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalobservationrun',
            name='aux_objects_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalobservationrun',
            name='aux_objects_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], default='', max_length=16),
        ),
    ]
