# Generated by Django 6.0.7 on 2026-07-24 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_run', '0010_observationrun_aux_objects_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='access_token_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['status', 'created_at'], name='dljob_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['user', 'status'], name='dljob_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['access_token_hash'], name='dljob_token_hash_idx'),
        ),
    ]
