# Generated by Django 4.2.4 on 2023-09-23 22:37

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIdentifier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('href', models.CharField(blank=True, max_length=400)),
                ('info_from_header', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical identifier',
                'verbose_name_plural': 'historical identifiers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalObject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('ra', models.FloatField(default=-1)),
                ('dec', models.FloatField(default=-1)),
                ('first_hjd', models.FloatField(default=0.0)),
                ('is_main', models.BooleanField(default=True)),
                ('photometry', models.BooleanField(default=False)),
                ('spectroscopy', models.BooleanField(default=False)),
                ('simbad_resolved', models.BooleanField(default=False)),
                ('object_type', models.CharField(choices=[('GA', 'Galaxy'), ('SC', 'Star cluster'), ('NE', 'Nebula'), ('SO', 'Solar system'), ('ST', 'Star'), ('OT', 'Other'), ('UK', 'Unknown')], default='UK', max_length=2)),
                ('note', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical object',
                'verbose_name_plural': 'historical objects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('href', models.CharField(blank=True, max_length=400)),
                ('info_from_header', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('ra', models.FloatField(default=-1)),
                ('dec', models.FloatField(default=-1)),
                ('first_hjd', models.FloatField(default=0.0)),
                ('is_main', models.BooleanField(default=True)),
                ('photometry', models.BooleanField(default=False)),
                ('spectroscopy', models.BooleanField(default=False)),
                ('simbad_resolved', models.BooleanField(default=False)),
                ('object_type', models.CharField(choices=[('GA', 'Galaxy'), ('SC', 'Star cluster'), ('NE', 'Nebula'), ('SO', 'Solar system'), ('ST', 'Star'), ('OT', 'Other'), ('UK', 'Unknown')], default='UK', max_length=2)),
                ('note', models.TextField(blank=True, default='')),
            ],
        ),
    ]
