# Generated by Django 4.2.4 on 2023-09-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        ('obs_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='datafiles',
            field=models.ManyToManyField(blank=True, to='obs_run.datafile'),
        ),
        migrations.AddField(
            model_name='object',
            name='observation_run',
            field=models.ManyToManyField(blank=True, to='obs_run.observationrun'),
        ),
    ]
