# Generated by Django 4.2.4 on 2023-09-23 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0002_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object'),
        ),
    ]
