# Generated by Django 5.2.8 on 2026-02-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_historicalobject_dec_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobject',
            name='exclude_from_orphan_cleanup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='exclude_from_orphan_cleanup',
            field=models.BooleanField(default=False),
        ),
    ]
