# Generated by Django 6.0.3 on 2026-05-21 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_type', models.CharField(db_index=True, max_length=32)),
                ('model_label', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=16)),
                ('instance_id', models.BigIntegerField(blank=True, null=True)),
                ('entity_label', models.CharField(max_length=255)),
                ('entity_path', models.CharField(blank=True, default='', max_length=255)),
                ('change_reason', models.CharField(blank=True, default='', max_length=100)),
                ('is_batch', models.BooleanField(default=False)),
                ('batch_count', models.PositiveIntegerField(default=1)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'model_type'], name='adminops_au_created_432829_idx')],
            },
        ),
    ]
